services:
  keelson-processor-sbg:
    build: .
    # image: ghcr.io/your-org/sbg-logger:latest  # optional if pushing to registry
    container_name: sbg-logger
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    command: >
      sbgBasicLogger -s /dev/ttyUSB0 -r 115200 -p